In [11]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("..")

import PIL
from src.dataset import get_load_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [22]:
train, test = get_load_data(root = "../../data", dataset = "VOCSegmentation", download = False)  
img, smnt = train[0] 

In [21]:
for _, smnt in train:
    smnt = np.asarray(smnt)
    print (np.unique(np.asarray(smnt)))

[  0   1  15 255]
[  0  20 255]
[  0   9  12 255]
[  0   3 255]
[  0  20 255]
[  0   5  15 255]
[  0   4 255]
[  0   1 255]
[  0   5  11 255]
[  0   1 255]
[  0  19 255]
[  0   3 255]
[  0  14  15 255]
[  0  13  15 255]


KeyboardInterrupt: 